### ISSUE TITLE
Simulation and Emulation 

### ISSUE THREAD

**Issue by zcysun** [Derekabc/MARL_CAVs#44]
Hello!

Currently, the simulation and emulation process involves fixed durations and numbers of vehicles, with each episode restarting from zero after it ends. Has the author considered fixing only the traffic scenario (such as a ramp junction) and generating vehicles at regular intervals, not starting and ending with an episode, but using simulation time for long-term training?

This approach seems to allow for a more comprehensive evaluation of the simulation process from multiple aspects, such as throughput, collision rate, and so on.

Best wishes!

**Comment by DongChen06** [comment]
Hi, thanks for your suggestion. Yes, it is possible to do that, since our algorithm is based on offline buffer. In our scenarios, in each episode, the number of vehicles changes from 2-6 (easy), 4-8 (medium), and 7-11 (hard), which will not affect our algorithms. So to add a continuous traffic flow, you can modify the vehicle generation function in the merge_env.

**Comment by zcysun** [comment]
Hello!
The training is evaluated at regular intervals. So, does the evaluation process give feedback on the training process? Or does the evaluation only read and collect relevant information and does not affect the training process?
